# Generated by Django 5.0.7 on 2024-07-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0003_remove_movie_actors_remove_movie_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='movie_id',
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(to='Movie.actor'),
        ),
    ]
