<<<<<<< HEAD
# Generated by Django 5.0.7 on 2024-07-15 05:57
=======
# Generated by Django 5.0.6 on 2024-07-15 06:15
>>>>>>> 4cf6d96 (버리고픈내코드)

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
<<<<<<< HEAD

    dependencies = [
        ('Movie', '0004_remove_actor_movie_id_movie_actors'),
=======
    dependencies = [
        ("Movie", "0004_remove_actor_movie_id_movie_actors"),
>>>>>>> 4cf6d96 (버리고픈내코드)
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
<<<<<<< HEAD
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
=======
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
>>>>>>> 4cf6d96 (버리고픈내코드)
        ),
    ]
